[package]
name = "idapro"
version = "0.1.0"
authors = ["Sam L. Thomas <st@simulacra.to>", "Chris M Stone <c.mcmahonstone@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.1"
regex = "1"
tempfile = "3.1"
snafu = "0.6.8"